# .github/workflows/build.yml

name: Build v4l2loopback Kernel Module

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build v4l2loopback.ko
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools & headers
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libelf-dev linux-headers-$(uname -r)

      - name: Build v4l2loopback
        run: |
          make -C . KERNELDIR=/lib/modules/$(uname -r)/build

      - name: Upload built module
        uses: actions/upload-artifact@v4
        with:
          name: v4l2loopback-module
          path: v4l2loopback.ko
